require('plugins')
require('options')
require('telescope-config')
require('nvim-cmp-config')
require('theme-onenord-config')
require('tree-sitter-config')
require('nvim-tree-config')
require('colorizer-config')
require('vgit-config')
require('lualine-config')
require('bufferline-config')

